### ISSUE TITLE
Does not compile on macOS

### ISSUE THREAD

**Issue by alessiamarcolini** [alexrenz/lapse-ps#1]
While compiling the project using `make`, I receive the following error:

```bash
tests/test_sampling.cc:148:23: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 
'std::__1::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 
4022730752, 18, 1812433253>::result_type' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
```

I use macOS 10.15.7

Full standard output here:
[lapse_compile_output.txt](https://github.com/alexrenz/lapse-ps/files/7563045/lapse_compile_output.txt)

**Comment by alexrenz** [comment]
We have not tried to run Lapse on macOS, as it is developed mostly for Linux servers. As discussed, I would recommend to try to compile with g++, but ultimately, I would recommend to run on Linux. If you make any progress on running this on macOS, please let me know so I can update the documentation, and make appropriate changes to the code base.
